
"""add image_url to models

Revision ID: 9e7a27b3d3a7
Revises: 846d2a645c80
Create Date: 2024-07-29 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7a27b3d3a7'
down_revision: Union[str, None] = '846d2a645c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('shop_categories', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('shops', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('device_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token')
    op.drop_column('users', 'image_url')
    op.drop_column('shops', 'image_url')
    op.drop_column('shop_categories', 'image_url')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
