from .commission import router as commission
from .marketplace import router as marketplace
from .health import router as health
from .auth_login import router as auth_login
from .auth_verify import router as auth_verify
from .admin_order import router as admin_order
from .shop_profile import router as shop_profile
from .parcel import router as parcel
from .order_flow import router as order_flow
from .admin_shop import router as admin_shop
from .ws import router as ws
from .rider import router as rider
from .discount import router as discount
from .auth_signup import router as auth_signup
from .ads import router as ads
from .admin_stats import router as admin_stats
from .mandla import router as mandla
from .rider_auth import router as rider_auth
from .uploads import router as uploads
from .admin_rider import router as admin_rider
from .rider_tasks import router as rider_tasks
from .admin_subscription import router as admin_subscription
from .notification import router as notification
from .support import router as support
from .riders import router as riders
from .shop import router as shop
from .cart import router as cart
from .admin_parcel import router as admin_parcel
from .auth_otp import router as auth_otp
from .udhar import router as udhar
from .order_proofs import router as order_proofs
from .shop_registration import router as shop_registration
from .rating import router as rating
from .rider_registration import router as rider_registration
from .users import router as users
from .shop_order import router as shop_order
from .auth_password import router as auth_password
from .order import router as order
from .auth_logout import router as auth_logout
from .auth_refresh import router as auth_refresh
from .auth_sessions import router as auth_sessions
from .wallets import router as wallets
from .kyc import router as kyc
from .admin_ledger import router as admin_ledger
from .product import router as product
from .subscription import router as subscription
from .withdrawal import router as withdrawal
from .logistics import router as logistics
from .website import router as website
from .payment import router as payment
from .admin_management import router as admin_management
from .dashboard import router as dashboard
from .admin_auth import router as admin_auth
from .auth_forgot import router as auth_forgot
from .admin_finance import router as admin_finance
from .gateway import router as gateway
